### ISSUE TITLE
the npm install instructions don't work

### ISSUE THREAD

**Issue by hayesmaker** [ekelokorpi/panda.js-engine#164]
These instructions are out of date:

http://www.pandajs.net/download/

`panda install` isn't an available command on panda

And you shouldn't sudo npm install anything.

```
➜  hayesmaker  panda create panda-thrust
Creating new project...
Done
➜  hayesmaker  cd panda-thrust
➜  panda-thrust  panda build
Building project...
/usr/local/lib/node_modules/pandatool/build.js:83
    for (var i = 0; i < pandaCore._coreModules.length; i++) {
                                              ^
TypeError: Cannot read property 'length' of undefined
    at Object.module.exports.exports [as build] (/usr/local/lib/node_modules/pandatool/build.js:83:47)
    at Object.<anonymous> (/usr/local/lib/node_modules/pandatool/panda.js:7:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by ekelokorpi** [comment]
You should use v1 toolkit, if using v1 engine.

    npm install -g pandatool@1.12.3

**Comment by ekelokorpi** [comment]
New site will be released, when v2 is ready.
